apiVersion: apps/v1
kind: Deployment
metadata:
  name: cesarapp
  labels:
    app: cesarapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cesarapp
  template:
    metadata:
      labels:
        app: cesarapp
    spec:
      containers:
        - name: cesarapp-container
          image: sosicker/cesarapp:latest  # Cambia por tu usuario de Docker Hub
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cesarapp-service
spec:
  selector:
    app: cesarapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000